//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPractika.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int IdAssignment { get; set; }
        public int IdUsers { get; set; }
        public int IdEquipment { get; set; }
        public System.DateTime DateAssignment { get; set; }
        public Nullable<System.DateTime> ReturnDateAssignment { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Users Users { get; set; }
    }
}
