//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPractika.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Assignment = new HashSet<Assignment>();
            this.Maintenance = new HashSet<Maintenance>();
            this.Price = new HashSet<Price>();
        }
    
        public int IdEquipment { get; set; }
        public string NameEquipment { get; set; }
        public string TypeEquipment { get; set; }
        public string ModelEquipment { get; set; }
        public string SerialNumberEquipment { get; set; }
        public Nullable<System.DateTime> PurchaseDateEquipment { get; set; }
        public Nullable<int> WarrantyPeriodEquipment { get; set; }
        public Nullable<int> IdLocation { get; set; }
        public string StatusEquipment { get; set; }
        public int IdSuppliers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignment { get; set; }
        public virtual Location Location { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Price { get; set; }
    }
}
