//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPractika.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int IdMaintenance { get; set; }
        public int IdEquipment { get; set; }
        public System.DateTime DateMaintenance { get; set; }
        public string DescriptionMaintenance { get; set; }
        public string PerformedMaintenance { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
