//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPractika.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int IdPrice { get; set; }
        public int IdEquipment { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
